### ISSUE TITLE
Doesnt seem to load for me, i just get a funny mouse cursor

### ISSUE THREAD

**Issue by wifiuk** [x3omdax/PenBox#12]
i get this and it just sits there, 

http://pix.toile-libre.org/upload/original/1471890544.jpg

**Comment by spythedude** [comment]
Try python penbox.py

**Comment by wifiuk** [comment]
Same

**Comment by x3omdax** [comment]
terminal : cd Desktop && git clone https://github.com/x3omdax/PenBox.git && cd PenBox && python penbox.py
